# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
source "$HOME/.dotfiles/paths"

#mkdir -p .zsh_hist
#HISTFILE=$HOME/.zsh_hist/global
#if [[ $TMUX_PANE ]]; then
#  HISTFILE=$HOME/.zsh_hist/tmux_${TMUX_PANE:1}
#fi

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.dotfiles/oh-my-zsh"

ZSH_THEME="ssipos"

# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# HIST_STAMPS="dd/mm/yyyy"

plugins=(git-prompt tmux tmuxinator)

source $ZSH/oh-my-zsh.sh

# export MANPATH="/usr/local/man:$MANPATH"

export EDITOR='vim'
export PATH="/home/ssipos/.local/bin:$PATH"

alias ll="ls -laF"
alias dc="docker-compose"
alias fucking="sudo"
alias vim="emacsclient -nw"

