# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

if [[ -f "$HOME/.dotfiles/paths" ]]; then
  source "$HOME/.dotfiles/paths"
fi

# Path to your oh-my-zsh installation.
ZSH="/usr/local/share/ohmyzsh"

#ZSH_THEME="robbyrussell"
ZSH_THEME="ssipos"

CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

HIST_STAMPS="dd/mm/yyyy"

plugins=(ssipos-git-prompt)

export EDITOR='vim'

source $ZSH/oh-my-zsh.sh

alias ll="ls -laF"
alias dc="docker-compose"
alias fucking="sudo"
alias em="emacsclient"
alias ec="emacsclient"

function dlog () {
  CONTAINER_ID=$(docker-compose ps -q $1)
  if [ $? -eq 0 ]; then
    docker logs -f $CONTAINER_ID
  else
    >&2 echo "Error finding container."
  fi
}

