#!/bin/sh
set -ux

WHOAMI=$(whoami)
HOSTNAME=$(hostname)

WINDOW_TITLE="$WHOAMI@$HOSTNAME -- tmux"
TMUX_WINDOW=$(xdotool search --name "$WINDOW_TITLE")

TEMULATOR="alacritty --title=\"$WINDOW_TITLE\" -e tmux -f $HOME/.tmux/tmux.conf"
command -v alacritty2 > /dev/null
if [ $? -ne 0 ]; then
    TEMULATOR="gnome-terminal --geometry=240x50+100+0 --title=\"$WINDOW_TITLE\" -- tmux -f $HOME/.tmux/tmux.conf"
fi

if [ "$TMUX_WINDOW" = "" ]; then
    eval $TEMULATOR &
    kill $$
fi

if [ "$(xdotool getwindowfocus)" = "$TMUX_WINDOW" ]; then
    ACTION=windowminimize
else
    ACTION=windowactivate
fi


exec xdotool $ACTION $TMUX_WINDOW
