#!/bin/sh
set -ux

WINDOW_TITLE="main-tmux"
TMUX_WINDOW=$(xdotool search --name "$WINDOW_TITLE")

if [ "$TMUX_WINDOW" = "" ]; then
    alacritty --class="$WINDOW_TITLE" --title="$WINDOW_TITLE" --command="attach-tmux" &
    kill $$
fi

ACTION=windowactivate

exec xdotool $ACTION $TMUX_WINDOW --sync

