#!/bin/sh
set -ux

WHOAMI=$(whoami)
HOSTNAME=$(hostname)

WINDOW_TITLE="$WHOAMI@$HOSTNAME -- tmux"
TMUX_WINDOW=$(xdotool search --name "$WINDOW_TITLE")

if [ "$TMUX_WINDOW" = "" ]; then
    xfce4-terminal --geometry="240x50+100+0" --title="$WINDOW_TITLE" --command="start-tmux" &
    kill $$
fi

ACTION=windowactivate

exec xdotool $ACTION $TMUX_WINDOW --sync

